fixtures+ tests
profcomff/rating-api pull request #49
Opened 2024-11-11 20:46 UTC by Zimovchik

## Изменения

## Детали реализации

## Check-List

- [ ] Вы проверили свой код перед отправкой запроса?
- [ ] Вы написали тесты к реализованным функциям?
- [ ] Вы не забыли применить форматирование `black` и `isort` для _Back-End_ или `Prettier` для _Front-End_?

2024-11-11 21:03 UTC, parfenovma requested changes
Вань, у тебя фикстуры используются как функции
тогда это уже не фикстуры получаются)

2024-11-11 21:03 UTC, parfenovma commented on tests/test_routes/test_comment.py
> +    response = client.get(f'{url}', params=query)
а у нас есть возможность потестить со скоупами, когда будет не 403? чтобы тоже покрытие было

2024-11-11 21:06 UTC, Zimovchik commented on rating_api/utils/utils.py
> +    return random.randint(-2, 2)
я это просто у Семы скатал в другой репке)

2024-11-11 21:06 UTC, Zimovchik commented on rating_api/utils/utils.py
> +    return random.randint(-2, 2)
рандом строку который

2024-11-11 21:07 UTC, Zimovchik commented on tests/test_routes/test_comment.py
> +    response = client.get(f'{url}', params=query)
я спросил у Темы, пока не понял как туда скоупы засунуть, все что я пытался сделать не сработало

2024-11-11 21:13 UTC, Zimovchik commented on rating_api/utils/utils.py
> +    return random.randint(-2, 2)
> объясню: рандом сложно дебажить + он может давать false positive тесты
> 
> вот записал ты в базу радном строку. В каком тесте она записалась? Когда она туда записалась: когда ты сейчас тесты прогнал или в прошлый раз?

вообще невозможен кейс когда она запишется в бд и там останется, во всех фикстурах прописан клин ап, даже если тест падает все из бд удалится

2024-11-11 21:20 UTC, Zimovchik commented
перепишу

2024-11-11 21:24 UTC, parfenovma commented on tests/test_routes/test_comment.py
> +    params = {"lecturer_id": 1}
У тебя же на 404 проверка)

2024-11-11 21:24 UTC, parfenovma commented on tests/test_routes/test_comment.py
> +    response = client.get(f'{url}', params=query)
Давай тогда так оставим если нет механизма как это тестировать или мокать

2024-11-11 21:25 UTC, parfenovma commented on rating_api/utils/utils.py
> +    return random.randint(-2, 2)
> я это просто у Семы скатал в другой репке)

Хехех
Ну мы тогда молодыми ещё были, перепишем потом

2024-11-12 14:49 UTC, parfenovma approved these changes

2024-11-14 20:12 UTC, Temmmmmo reviewed
норм, комменты подправь(или ответь) и аппрувну

2024-11-14 20:12 UTC, Temmmmmo commented on tests/conftest.py
> +    _lecturer = Lecturer(first_name="test_fname", last_name="test_lname", middle_name="test_mname", timetable_id=0)
лучше таймтейбл айди наоборот большим сделать

2024-11-14 20:12 UTC, Temmmmmo commented on tests/conftest.py
> +    dbsession.refresh(_lecturer)
рефреш разфе нужен?

2024-11-14 20:25 UTC, Temmmmmo commented on tests/test_routes/test_comment.py
> +    assert post_response.status_code == response_status
response_status откуда приходит?

2024-11-14 20:25 UTC, Temmmmmo commented on tests/test_routes/test_comment.py
> +    'body,timetable_id,response_status',
а, вот он

2024-11-14 20:25 UTC, Temmmmmo commented on tests/test_routes/test_lecturer.py
> +    assert json_response['first_name'] == 'test_fname'
лучше не 'test_fname', а lecturer['first_name']

2024-11-14 20:25 UTC, Temmmmmo commented on tests/test_routes/test_lecturer.py
> +    assert json_response['last_name'] == 'test_lname'
аналогично

2024-11-14 20:25 UTC, Temmmmmo commented on tests/test_routes/test_lecturer.py
> +    assert json_response['middle_name'] == 'test_mname'
аналогично

2024-11-14 20:25 UTC, Temmmmmo commented on tests/test_routes/test_lecturer.py
> +    assert "test_subject" in json_response["subjects"]
тоже бери из фикстуры это

2024-11-14 20:25 UTC, Temmmmmo commented on tests/test_routes/test_lecturer.py
> +    assert "test_subject1" in json_response["subjects"]
тоже бери из фикстуры это

2024-11-14 20:25 UTC, Temmmmmo commented on tests/test_routes/test_lecturer.py
> +    assert "test_subject2" not in json_response["subjects"]
тоже бери из фикстуры это

2024-11-14 20:25 UTC, Temmmmmo commented on tests/test_routes/test_comment.py
> +def test_review_comment(client, dbsession, unreviewed_comment, review_status, response_status):
надо еще попробовать аппрувнуть аппрувнутый
диссмиснуть аппрувнутый? (че будет кстати, я щас так не скажу даже)

2024-11-14 20:25 UTC, Temmmmmo commented on tests/test_routes/test_comment.py
> +def test_comments_by_lecturer_id(client, lecturers_with_comments, timetable_id, response_status):
давай попробуем получить комменты несуществующего лектора еще

2024-11-14 20:25 UTC, Temmmmmo commented on tests/test_routes/test_lecturer.py
>      body = {"first_name": 'Иван', "last_name": 'Иванов', "middle_name": 'Иванович', "timetable_id": 0}
опять же таймтейбл айди надо большим сделать

2024-11-14 20:25 UTC, Temmmmmo commented on tests/test_routes/test_comment.py
> +                "mark_kindness": 5,
елси deleted_lecturer, то норм оценку тут сделай, а-то мб из-за этого 400 приходит

2024-11-14 20:29 UTC, Temmmmmo commented
там еще тимур убрал регистрозависимость при поиске
тест на это тоже добавь))

2024-11-15 03:54 UTC, Zimovchik commented on tests/test_routes/test_lecturer.py
>      body = {"first_name": 'Иван', "last_name": 'Иванов', "middle_name": 'Иванович', "timetable_id": 0}
почему?

2024-11-15 03:56 UTC, Zimovchik commented on tests/conftest.py
> +    dbsession.refresh(_lecturer)
ну тут он скорее safety_check, но вообще да, нужно поддерживать актуальность данных в фикстурах, например если мы меняем что-то в ней напрямую обращаясь в бд они не всегда тривиально обновляются сами

2024-11-15 03:57 UTC, Zimovchik commented on tests/conftest.py
> +    dbsession.refresh(_lecturer)
если посмотришь в самих тестах, там много где рефреш стоит перед тем, как смотреть изменились ли данные в фикстуре, потому что без этого не работает. Это просто замена полноценного запроса в бд как было раньше

2024-11-15 03:58 UTC, Zimovchik commented on tests/conftest.py
> +    _lecturer = Lecturer(first_name="test_fname", last_name="test_lname", middle_name="test_mname", timetable_id=0)
а есть разница? типо больше кол-ва преподов поставить его хочешь?

2024-11-15 11:24 UTC, Temmmmmo commented on tests/test_routes/test_lecturer.py
>      body = {"first_name": 'Иван', "last_name": 'Иванов', "middle_name": 'Иванович', "timetable_id": 0}
0 может быть занят, а слишком большой на вряд ли

2024-11-16 12:35 UTC, merged