added create_ts and update_ts to create_comment
profcomff/rating-api pull request #50
Opened 2024-11-15 18:38 UTC by zipperman1

## Изменения
добавлена возможность указать время создания и изменения комментария для админов

## Детали реализации
проверка на скоуп rating.comment.review
заменяем None на utcnow если дата на указана
скипаем проверку времени если у автора есть скоуп

## Check-List
- [ ] Вы проверили свой код перед отправкой запроса?
- [ ] Вы написали тесты к реализованным функциям?
- [ ] Вы не забыли применить форматирование `black` и `isort` для _Back-End_ или `Prettier` для _Front-End_?

2024-11-16 15:48 UTC, Zimovchik requested changes
надо потестить локально + дописать тесты

2024-11-16 15:48 UTC, Zimovchik commented on rating_api/routes/comment.py
> +                comment_info.create_ts = datetime.datetime.utcnow()
`comment_info.create_ts = datetime.datetime.utcnow() if comment_info.create_ts is None`

2024-11-16 15:48 UTC, Zimovchik commented on rating_api/routes/comment.py
> +                comment_info.update_ts = datetime.datetime.utcnow()
аналогично

2024-11-16 15:48 UTC, Zimovchik commented on rating_api/routes/comment.py
> +    if not "rating.comment.review" in [scope['name'] for scope in user.get('session_scopes')]:
`if smth not in list` - читается проще

2024-11-16 15:48 UTC, Zimovchik commented on rating_api/routes/comment.py
> +        if not "rating.comment.review" in [scope['name'] for scope in user.get('session_scopes')]:
`if smth not in list` - читается проще

2024-11-16 18:55 UTC, Zimovchik commented on rating_api/routes/comment.py
> +                comment_info.create_ts = datetime.datetime.utcnow()
думаю datetime.datetime.utcnow() можно вынести в отдельную переменную ты ее много раз юзаешь

2024-11-17 08:40 UTC, Zimovchik requested changes

2024-11-17 08:40 UTC, Zimovchik commented on rating_api/routes/comment.py
> +        if "rating.comment.review" not in [scope['name'] for scope in user.get('session_scopes')]:
Давай это тоже вынесем в что-то типо `has_review_scope: bool = ...`

2024-11-17 11:38 UTC, Zimovchik commented on rating_api/routes/comment.py
> +        comment_info.update_ts = current_time
```if comment_info.create_ts or comment_info.update_ts and not has_review_scope:
    raise ForbiddenAction(Comment)
if not comment_info.create_ts:
    ...
if not comment_info.update_ts:
   ...
```

2024-11-18 18:13 UTC, Zimovchik requested changes

2024-11-18 18:13 UTC, Zimovchik commented on rating_api/routes/comment.py
> +    Скоуп нужен для создания комментариев с заданым timestamp
@Temmmmmo посмотри как лучше доку написать

2024-11-18 18:13 UTC, Zimovchik commented on tests/test_routes/test_comment.py
> +        ),
добавь кейс некорректной даты

2024-11-22 14:04 UTC, Temmmmmo commented on rating_api/routes/comment.py
> +    Скоуп нужен для создания комментариев с заданым timestamp
"Для возможности создания комментария с указанием времени создания необходим скоуп `["rating.comment.review"]`"

2024-11-22 14:04 UTC, Temmmmmo commented on rating_api/routes/comment.py
> +            if current_time - user_comment.update_ts < datetime.timedelta(
давай все же не будем отдельную переменную current_time заводить, оставь как было

2024-11-24 13:32 UTC, Temmmmmo commented on rating_api/routes/comment.py
> +    Scopes: `["rating.comment.review"]`
А почему такой скоуп? Надо же rating.comment.create

2024-11-24 13:32 UTC, Temmmmmo commented on rating_api/routes/comment.py
> +    has_review_scope = "rating.comment.review" in [scope['name'] for scope in user.get('session_scopes')]
rating.comment.create

2024-11-24 13:32 UTC, Temmmmmo commented on rating_api/routes/comment.py
> +    if not comment_info.create_ts:
это не надо, у нас в базе автоматически проставляется, если не передается

2024-11-24 13:32 UTC, Temmmmmo commented on rating_api/routes/comment.py
> +    if not comment_info.create_ts:
в базе дефолт стоит

2024-11-24 14:48 UTC, Zimovchik commented
резолвни конфликты

2024-11-24 17:16 UTC, Zimovchik approved these changes

2024-11-24 21:28 UTC, Temmmmmo commented on rating_api/routes/comment.py
>      user_comments: list[LecturerUserComment] = (
давай запрос в бд вынесем отдельно под if not has_create_scope

2024-11-24 21:54 UTC, merged