add user_id to get_comments and bugfix
profcomff/rating-api pull request #56
Opened 2024-11-18 16:50 UTC by zipperman1

## Изменения
добавил возможность фильтровать комментарии по user_id

## Детали реализации
Добавил параметр функции get_comments user_id

## Check-List
- [x] Вы проверили свой код перед отправкой запроса?
- [x] Вы написали тесты к реализованным функциям?
- [x] Вы не забыли применить форматирование `black` и `isort` для _Back-End_ или `Prettier` для _Front-End_?

2024-11-18 18:05 UTC, Zimovchik requested changes
вроде все норм, тесты ток поправь

2024-11-18 18:05 UTC, Zimovchik commented on tests/conftest.py
> +        (lecturers[0].id, 1, 'test_subject11', ReviewStatus.APPROVED, 1, 1, 1),
давай user_id большой сделаем, переделай мои инсерты тоже с 0 на что-то  большое

2024-11-19 17:31 UTC, Zimovchik approved these changes

2024-11-22 14:06 UTC, Temmmmmo reviewed
надо сделать это через проперти для таблицы, Тимур такое делал
у него в ПРе для сортировки есть. посмотри
ну или просто доку алхимии прочитай)

2024-11-24 13:37 UTC, merged