Make patch route #10
profcomff/rating-api pull request #60
Opened 2024-11-23 13:03 UTC by DR0P-database

## Изменения #10 

ВАЖНО: изменена ручка для patch/review комментария админами

Чтобы изменить комментарий ему нужно отправить все поля для схемы CommentPost, их можно предварительно получить из GET, и в комментарии перепишутся поля. Также можно сделать комментарий анонимным через PATCH.

## Детали реализации

## Check-List
- [x] Вы проверили свой код перед отправкой запроса?
- [x] Вы написали тесты к реализованным функциям?
- [x] Вы не забыли применить форматирование `black` и `isort` для _Back-End_ или `Prettier` для _Front-End_?

2024-11-24 13:49 UTC, Temmmmmo reviewed
Сделай тогда новую модельку и поправь тесты и код

2024-11-24 13:49 UTC, Temmmmmo commented on rating_api/routes/comment.py
> +    Изменить комментарий только свой неанонимный.
Позволяет изменить свой неанонимный комментарий

2024-11-24 13:49 UTC, Temmmmmo commented on rating_api/routes/comment.py
> +    Должны быть переданы все поля в теле запроса: оценки, предмет, текст. Их можно получить из GET и изменить нужное, остальное оставить
Ну тут разберутся люди на фронте) не надо так подробно, откуда что можно получить

2024-11-24 13:49 UTC, Temmmmmo commented on rating_api/routes/comment.py
> +async def update_comment(uuid: UUID, comment_update: CommentPost = None, user=Depends(UnionAuth())) -> CommentGet:
Давай создадим отдельную модельку вида:

```
class CommentUpdate(Base):
    subject: str
    text: str
    mark_kindness: int
    mark_freebie: int
    mark_clarity: int
    
    @field_validator('mark_kindness', 'mark_freebie', 'mark_clarity')
    @classmethod
    def validate_mark(cls, value):
        if value not in [-2, -1, 0, 1, 2]:
            raise WrongMark()
        return value
```

is_anonymous нам тут ненужно, так как если можно обновить комментарий, то он подразумевается неанонимным

2024-11-24 13:51 UTC, Temmmmmo commented on rating_api/routes/comment.py
> +    if comment.user_id != user.get("id"):
еще надо учесть, что если вдруг comment.user_id is None, то тоже рейзим 403, т.к. анонимные не меняются

2024-11-24 14:11 UTC, DR0P-database commented on rating_api/routes/comment.py
> +    user_id = None if comment_update.is_anonymous else comment.user_id
Это для того чтобю свой НЕанонимный комментарий сделать анонимным

2024-11-24 21:25 UTC, Temmmmmo commented on rating_api/routes/comment.py
> +    user_id = None if comment_update.is_anonymous else comment.user_id
ну такое поведение очень странное, анонимность/неанонимность это, скорее, константное свойство, присущее каждому комментарию
если человек хочет поменять неанонимный на анонимный, то лучше будет просто создать новый коммент, а старый удалить

2024-11-24 23:39 UTC, DaymasS commented on rating_api/routes/comment.py
> +            **comment_update.model_dump(exclude=set(k for k, v in comment_update if v is None)),
exclude_unset=True

2024-11-25 04:09 UTC, Zimovchik requested changes

2024-11-25 04:09 UTC, Zimovchik commented on tests/conftest.py
> +def comment_update(dbsession, lecturer):
зачем эта фикстура, в чем ее принципиальная разница с comment?

2024-11-25 04:09 UTC, Zimovchik commented on tests/test_routes/test_comment.py
> +    if response.status_code == status.HTTP_200_OK:
проверь еще, что что-то реально поменялось(текст/оценка)

2024-11-25 05:06 UTC, Zimovchik commented on tests/conftest.py
> +def comment_update(dbsession, lecturer):
если дело в том, что там не указан user_id, можешь указать, поидее это ничего не сломает

2024-11-25 10:09 UTC, DR0P-database commented on tests/conftest.py
> +def comment_update(dbsession, lecturer):
В коде стоит проверка на user_id, а в тестах в фикстуре comment, user_id автоматически проставляется null, как можно это пофиксить(в тестах/в микстурах)?

2024-11-25 10:14 UTC, DR0P-database commented on tests/test_routes/test_comment.py
> +    if response.status_code == status.HTTP_200_OK:
Зачем?

2024-12-01 18:21 UTC, Temmmmmo commented on rating_api/routes/comment.py
> +    """Позволяет изменить свой неанонимный комментарий. любое поле опционально,"""
Оставь просто `Позволяет изменить свой неанонимный комментарий`

2024-12-01 18:21 UTC, Temmmmmo commented on tests/test_routes/test_comment.py
> +    if response.status_code == status.HTTP_200_OK:
Ваня прав)
Надо бы сделать сделать запрос и сравнить со старым

2024-12-01 18:21 UTC, Temmmmmo commented on tests/test_routes/test_comment.py
> +            {},
это не норм поведение
давай, если ничего не меняется, то возвращать 409

2024-12-06 18:51 UTC, Zimovchik commented on rating_api/routes/comment.py
> +    # Если хоть одно поле было передано неизменным
а зачем это проверять в чем глобальная проблема что чел не меняет какую-то часть?

2024-12-06 18:55 UTC, parfenovma commented on rating_api/routes/comment.py
> +@comment.patch("/{uuid}/review", response_model=CommentGet)
warning!
надо поддерджать это на Фронте, перед выкаткой напишите Илье Батуеву

2024-12-06 18:55 UTC, parfenovma commented on rating_api/schemas/models.py
> +    mark_clarity: int = None
str | None = None etc.

2024-12-06 18:55 UTC, parfenovma commented on rating_api/routes/comment.py
> +            review_status=ReviewStatus.PENDING,
что коммент после патча пропадает из выдачи это ожидаемое поведение?
Понимаю, что здесь сложно по-другому реализовать, спрашиваю скорее обсуждали ли вы это?

2024-12-06 18:55 UTC, parfenovma commented on rating_api/routes/comment.py
> +            update_ts=datetime.datetime.utcnow(),
это постгрес сам вроде может проставлять

2024-12-09 10:24 UTC, DR0P-database commented on rating_api/routes/comment.py
> +            update_ts=datetime.datetime.utcnow(),
<img width="488" alt="image" src="https://github.com/user-attachments/assets/538bf929-6f47-4d15-9104-57a02f7d1658">
<img width="408" alt="image" src="https://github.com/user-attachments/assets/50a82e29-ba31-4976-b20b-eb279294351b">

Если не обновлять вручную(закоментить эту строчку) в коде то Postgres не сделает

2024-12-09 10:25 UTC, DR0P-database commented on rating_api/schemas/models.py
> +    mark_clarity: int = None
Тогда можно передавать None значение в Swagger

2024-12-09 10:29 UTC, DR0P-database commented on rating_api/routes/comment.py
> +    # Если хоть одно поле было передано неизменным
Артем скащал "не нормальное поведение если нету параметров"

2024-12-09 10:41 UTC, DR0P-database commented on tests/test_routes/test_comment.py
> +    if response.status_code == status.HTTP_200_OK:
Сделал

2024-12-09 10:43 UTC, DR0P-database commented on rating_api/routes/comment.py
> +            review_status=ReviewStatus.PENDING,
По логике его надо проверить, в БД старой версии комментария не остается => выдавать нечего

2024-12-09 10:56 UTC, parfenovma approved these changes

2024-12-09 10:58 UTC, Zimovchik approved these changes

2024-12-10 05:09 UTC, DaymasS commented on rating_api/routes/comment.py
> +    # Если хоть одно поле было передано неизменным
Кажется ты немного не так понял. Проверять, что какую-то часть не поменяли - не значит, что юзер должен абсолютно все данные другие ввести. Это же странно, что для того, чтобы изменить комментарий, нужно изменить каждое поле. Я даже предмет или одну оценку не смогу такую же оставить

2024-12-10 15:03 UTC, Temmmmmo requested changes

2025-03-07 20:40 UTC, merged