Recomment with has_create_scope
profcomff/rating-api pull request #66
Opened 2024-12-06 22:55 UTC by ValeryEstal

## Изменения

## Детали реализации

## Check-List

- [ ] Вы проверили свой код перед отправкой запроса?
- [ ] Вы написали тесты к реализованным функциям?
- [ ] Вы не забыли применить форматирование `black` и `isort` для _Back-End_ или `Prettier` для _Front-End_?

2024-12-06 23:05 UTC, DaymasS requested changes

2024-12-06 23:05 UTC, DaymasS commented on rating_api/routes/comment.py
В 52-й строке нужно добавить, чтобы LecturerUserComment имел create_ts и update_ts с точностью до месяца

2024-12-06 23:28 UTC, DaymasS commented on rating_api/routes/comment.py
> +    create_ts = datetime.datetime(datetime.datetime.now(ts=datetime.timezone.utc).year, datetime.datetime.now(ts=datetime.timezone.utc).month, 1)
current_month_start можно просто использовать

2024-12-06 23:32 UTC, DaymasS commented on rating_api/routes/comment.py
> +            raise TooManyCommentRequests(dtime=current_month_start)
dtime=current_month_start + datetime.timedelta(month=1) - datetime.datetime.utcnow()

Тебе нужно время оставшейся задержки

2024-12-08 16:54 UTC, DaymasS requested changes

2024-12-08 16:54 UTC, DaymasS commented on rating_api/routes/comment.py
> +        current_month_start = current_month_start
нужно проинициализировать current_month_start

2024-12-08 16:54 UTC, DaymasS commented on rating_api/routes/comment.py
> +        datetime.datetime.now(ts=datetime.timezone.utc).year, datetime.datetime.now(ts=datetime.timezone.utc).month, 1
create_ts = current_month_start

2024-12-09 22:24 UTC, DaymasS approved these changes

2024-12-10 15:09 UTC, Temmmmmo reviewed
самое главное не изменено
комментарии при создании сохраняются с точной датой создания, а нужно сохранять только месяц, нужно это пофиксить

2024-12-12 09:46 UTC, Temmmmmo requested changes

2024-12-12 09:46 UTC, Temmmmmo commented on rating_api/routes/comment.py
> +                ),
через timedelta может получиться неверно, т.к. у нас не во всех месяцах обязательно 30 или 31 день

2024-12-12 09:46 UTC, Temmmmmo commented on rating_api/routes/comment.py
> +            1,
_этот коммент читать после коммента про дельту_

давай сделаем сразу вот тут учитывание задержки, т.е. будем сразу создавать объект с нужным номером month

а потом будем просто сверять с этим

поэтому название переменной тоже стоит поменять на что-то типа limit_ts

2024-12-12 09:46 UTC, Temmmmmo commented on rating_api/routes/comment.py
> +            raise TooManyCommentRequests(
давай реализацию этой ошибки поменяем, пусть она возвращает просто что-то типа
"Превышен лимит комментариев. В N месяцев можно оставлять не более K комментариев."
Соответственно реализацию ошибки нужно поменять так, чтобы в нее можно было передавать эти параметры N и K, соответственно

2024-12-12 09:46 UTC, Temmmmmo commented on rating_api/routes/comment.py
> +    cutoff_date_lecturer = now - datetime.timedelta(days=30 * settings.MONTH_LECTURER_FREQUENCY) #  L месяцев назад
Здесь давай опять не через дельту сделаем, а сразу объект некоторый limit_lecturer_ts создадим

2024-12-12 09:46 UTC, Temmmmmo commented on rating_api/settings.py
> +    COMMENT_LECTURER_FREQUENCY: int = l
Почему 5 параметров и что такое k и l ?

2024-12-13 02:20 UTC, DaymasS requested changes

2024-12-13 02:20 UTC, DaymasS commented on rating_api/routes/comment.py
> +    current_month_start = datetime.datetime(now.year, now.month, 1)  # Начало текущего месяца
Now не проинициализирован

2024-12-13 02:20 UTC, DaymasS commented on rating_api/routes/comment.py
> +        now = datetime.datetime.now(tz=datetime.timezone.utc)
Соответственно эта инициализация должна проходить до первого использования now

2024-12-13 02:20 UTC, DaymasS commented on rating_api/routes/comment.py
> +        raise TooManyCommentsToLecturer(lecturer_id)
Эта логика должна входить в if на 38-й строке

2024-12-13 02:20 UTC, DaymasS commented on rating_api/settings.py
> +    COMMENT_LECTURER_FREQUENCE_IN_MONTH: int = 20
Надо будет уточнить точные константы, но 20 месяцев это слегка через чур🙃

2024-12-13 02:26 UTC, DaymasS commented on rating_api/routes/comment.py
> +        raise TooManyCommentsToLecturer(lecturer_id)
Также необходимо поправить реализацию ошибки ToMantRequests, чтобы она принимала и обрабатывала 2 аргумента

2024-12-14 19:20 UTC, DaymasS requested changes

2024-12-14 19:20 UTC, DaymasS commented on rating_api/routes/comment.py
> +from dateutil.relativedelta import relativedelta
Убрать, будем делать без этой библиотеки

2024-12-14 19:20 UTC, DaymasS commented on rating_api/routes/comment.py
> +now = datetime.datetime.now(tz=datetime.timezone.utc)
В таком случае в now положится дата запуска модуля, и в последствии обновляться не будет. 
Стоит перенести эту инициализацию  в начало функции create_comment

2024-12-14 19:20 UTC, DaymasS commented on rating_api/routes/comment.py
> +    current_month_start = datetime.datetime(now.year, now.month, 1)  # Начало текущего месяца
Удалить переменную

2024-12-14 19:20 UTC, DaymasS commented on rating_api/routes/comment.py
> +        date_count = current_month_start - relativedelta(months=settings.COMMENT_FREQUENCY_IN_MONTH)
```python3
date_count = datetime.datetime(now.year - (now.month - settings.COMMENT_FREQUENCY_IN_MONTH) // 12, (now.month - settings.COMMENT_FREQUENCY_IN_MONTH) % 12, 1)
```

2024-12-14 19:20 UTC, DaymasS commented on rating_api/routes/comment.py
> +    cutoff_date_lecturer = current_month_start - relativedelta(months=settings.COMMENT_LECTURER_FREQUENCE_IN_MONTH)
Аналогично date_count, но с другой константой

2024-12-14 19:20 UTC, DaymasS commented on rating_api/routes/comment.py
> +    create_ts = current_month_start
```python
create_ts = datetime.datetime(now.year, now.month, 1)
```

2024-12-15 13:36 UTC, Temmmmmo requested changes

2024-12-15 13:36 UTC, Temmmmmo commented on rating_api/routes/comment.py
> +#  pip install python-dateutil
комм убрать

2024-12-15 13:36 UTC, Temmmmmo commented on rating_api/routes/comment.py
> +            raise TooManyCommentRequests(settings.COMMENT_FREQUENCY_IN_MONTH, settings.COMMENT_LIMIT)
Модельку этой ошибки тоже надо переписать по аналогии с TooManycommentsToLecturer

2024-12-15 23:19 UTC, DaymasS approved these changes

2024-12-16 16:59 UTC, Temmmmmo approved these changes

2024-12-16 17:00 UTC, merged